### ISSUE TITLE
Does not work on Firefox for Mac

### ISSUE THREAD

**Issue by ocdude** [jinhofer/pastespecial#1]
The iframe is completely empty on firefox for mac. Works on Chrome, though.

![screen shot 2015-04-02 at 11 03 56 am](https://cloud.githubusercontent.com/assets/226313/6970057/faf917d0-d927-11e4-9d24-c648da416ec5.png)

**Comment by jinhofer** [comment]
You are very correct that it is not working on FF! I am looking into this now.

**Comment by jinhofer** [comment]
I changed the iframe to an editable div, which now works in FF, IE, Safari, and Chrome. Thank you for pointing this out to me!
