### ISSUE TITLE
Paste as unformatted text does not work if clipboard does not contain a paragraph.

### ISSUE THREAD

**Issue by bwl21** [jinhofer/pastespecial#11]
If clipboard does not contain a paragraph but only text.

To reproduce:

1. Paste (in plain html)

```html
<p>cut paste from here&gt; to <b>this</b> point &lt;to here</p>
```

2. switch to WYSYWIG
3. cut the phrase  "to this point"
4. invoke pasteSpecial
5. select "paste as plain text"
6. the right pane (preview) does not show any text.

**Comment by jinhofer** [comment]
I was able to reproduce this, and it is very strange behavior. It seems that when one proceeds to paste the edited text, it is simply wrapped in a span tag. Unformatted then strips the tag, but in doing so does not actually take the text within.

I have fixed this on the master branch, thank you for pointing it out!

**Comment by jinhofer** [comment]
I have fixed this in the new version on Moodle, thank you!

You might like to hear that I have added a bit of code to allow users to paste tables. I don't do anything with the table, just straight paste anything within <table></table>.
