### ISSUE TITLE
possible typo?

### ISSUE THREAD

**Issue by fhung65** [jinhofer/pastespecial#2]
I noticed in button.js, _handleStyle has a regular expression that looks like it might be a typo. 'noBreaks = current.replace(/\s+g/, '');'

**Comment by jinhofer** [comment]
fhung65,

Thank you for your comment! I have been traveling Europe for the past 2 months, so I apologize for the late response.

As for that line, the purpose is to remove all spaces to make the final product more aesthetically pleasing. If you are noting the difference between /\s+g/ and /\s/g/, in this case there will be none. I did look this up: http://stackoverflow.com/questions/5964373/is-there-a-difference-between-s-g-and-s-g

Is this what you are referring to? If not, could you be a bit more specific?

**Comment by fhung65** [comment]
I was originally referring to the lack of a '/' between the '+' and the 'g'. This stackoverflow post doesn't seem to exactly address it.

**Comment by fhung65** [comment]
It looked like the 'g' was supposed to come last, meaning global, as opposed to the literal character g

**Comment by jinhofer** [comment]
It looks like you're definitely right! I have changed it in the code and updated.
