### ISSUE TITLE
Not working in Chrome and Safari on Mac OS X

### ISSUE THREAD

**Issue by Kathrin84** [jinhofer/pastespecial#5]
I've tried out your plugin, but unfortunately it's not working in Chrome and Safari on my Mac.
It's opening the dialogue box and I can paste the text to the text area. I also can choose the format. When I click on the insert button, your plugin window closes and nothing happens in the original text area. There's simply no text in the atto text editor...
 
I've seen that you had the first issue where it did not work on Firefox. This is the only browser your plugin works fine with on my machine.

Kind regards
Kathrin

**Comment by jinhofer** [comment]
Kathrin,

What version of PasteSpecial are you using?

**Comment by Kathrin84** [comment]
I've installed your latest version 2015111300 and tried it again. Unfortunately it's still only working in Firefox. With the other browsers it doesn't work.

Cheers,
Kathrin

**Comment by jinhofer** [comment]
Kathrin,

Could you check console when you try to paste it from Chrome? It's possible that there is an error occurring that is stopping the code but not the page.

**Comment by Kathrin84** [comment]
Here's the console log from Chrome Browser when pasting text with your plugin.
I cannot see any hint for what's not working...
![console](https://cloud.githubusercontent.com/assets/4711883/11207913/5ecbef68-8d18-11e5-888d-b128a5c3f399.png)

**Comment by jinhofer** [comment]
That looks fine, so it's definitely not an issue with the JS crashing. Maybe it's an issue where it's not pasting the content at all because it thinks there's nothing in there. If you haven't yet, could you try pasting a different sample of text?

**Comment by Kathrin84** [comment]
I've always tried to paste a document that was created with a standard word template. In this template fields are embedded. I think it may depend on that.
If I take a simple word file pasting works in Safari and Chrome.

**Comment by jinhofer** [comment]
Hmm, that would make sense. I would say that it depends on the template whether or not it will paste. I think it's reasonable for some simple templates (without images or tables, at least) to paste well. What templates do you use? If you send me some sample documents, I can work on handling them.

**Comment by Kathrin84** [comment]
Hi, I took a quite simple template from word itself. I also only copied the main text and not header and footer.
The only thing that was pasted in this specific word file (https://github.com/Kathrin84/kathrin84_misc/blob/master/test.docx) was the last string (Geschäftsführerin). All text above did not make the way into the text editor.

**Comment by jinhofer** [comment]
I see where the issue was. Thank you for catching this! I believe that I have fixed this issue. Could you pull from the master branch and test again?

**Comment by jinhofer** [comment]
I have released a new version to Moodle! I'm going to close this ticket for now, but please keep me posted if you find any more issues or this one is not yet fixed.

**Comment by Kathrin84** [comment]
Hi,
in my test it's working fine now. Thanks for your effort!
