### ISSUE TITLE
make pastespecial the default

### ISSUE THREAD

**Issue by bwl21** [jinhofer/pastespecial#8]
Would it be possible to add a feature such that "paste from other" applies even if one uses cut/paste in ATTO without thinking about it. (e.g. using ctrl-c/ctrl-v).

In particular using chrome, cut/paste adds a lot of style pollution.

Maybe add another category "default cut - paste" to configure this behavior.

**Comment by jinhofer** [comment]
Interesting idea... I think that I might be able to work something out and make it an admin setting that can be turned on/off.

**Comment by bwl21** [comment]
Oh that would be great. This is exactly, what I thought of.

**Comment by jinhofer** [comment]
So to follow up more on this, are you wanting pastespecial to grab the text when a user pastes it and handles the text as if it is being pasted from other? Or would you rather that when the paste happens, the dialogue opens and the text is placed into the div so that the user can change where it's being pasted from before they click submit?

**Comment by bwl21** [comment]
My intention was indeed such that when a user pastes it, handles the text as if it is being pasted "from other". It comes from the fact that I would like to get  rather plain HTML.  But I admit there are other use cases as well.

Your second option brought me to the point that It might be even more user friendly since it provides a preview of what will happen, even if it is one click more (which could be a simple hit on return if the paste button has the focus by default. 

I played around with it and found that the dialog does show the content before it is cleaned up. If you could show a preview of the cleaned content, and provide the possibility to cycle through the available configurations, then the user can control what happens.

Is it possible to make the dialog wider 

BTW: it appears to filter tables entirely.

Thanks for following up.

**Comment by jinhofer** [comment]
So I have been playing around with this and I think I like your ideas! So I have done the following:

When a user uses a keyboard (ctrl/cmd+v but NOT ctrl/cmd+shift+v) to paste into atto, pastespecial will pop up and the text will be pasted into the box, and "Other" will be selected.
I've changed the popup:
![image](https://cloud.githubusercontent.com/assets/8837519/11935397/4545195a-a7cd-11e5-9cd0-07687c2da712.png)
You will note that the width has doubled.
A "preview" window has appeared.
I paste what's in the "preview" box, so if the user changes it a bit, that'll be pasted.
It's a live update, so any changes to the "paste" box will update the "preview" box (but overwrite it).
When the user changes the "paste from" shenanigans, the "preview" box will reflect this.

What do you think of these changes? I'm in the testing phase right now, so nothing is set in stone yet.

**Comment by jinhofer** [comment]
Also note, it shows the corrected unformatted paste.

**Comment by bwl21** [comment]
It is cool. So the user can select one of the options to see which gives best result? 

Is there a reason that this dialog is not resizeable? If yes; I would make it even wider (if not fullscreen). I know, hard to implement but could both views synced while scrolling?

Neverthelss I like it very much, since it drastically reduces the surprise.

If the options specifiy only an applicable filter, then I still wonder why we need the options? The result should have ony those styles supported by the current environment (which I would simply configure in 'other'). A different story is, if past special would even do a kind of transformation. This would be extremely cool but also hard to configure ...

It could even end in pasting markdown and getting HTML :-)

**Comment by jinhofer** [comment]
Yup, it gives an instant visual presentation before it's pasted.

The dialogue (the whole popup) that I am using is Moodle's core function. So it won't be resizeable, but I will skirt around that by setting its height and width using %, making it responsive to the page size.

The only reason we have the options is that certain origins will have different formatting styles. Google docs uses <li> for lists, but Word has a whole other world of how those are generated.

What do you mean by "transformation"?

Markdown might be easy (and I might eat my words on this one), but Moodle has a markdown text editor that you can use in place of Atto as well!

**Comment by bwl21** [comment]
Yes, I understant the different styles created by the various origins, in particular with respect to lists. Word only knows paragraphs and handles everything else using styles (This is why I definitely am not a friend of Word).

A **filter** strips styles, e.g.

`<p style="color:green">lorem ipsum</p>`

becomes

`<p>lorem ipsum</p>`

A **transformation** changes the structure

`<p style="list-style-type: circle;">lorem-ipsum</p>`

becomes

`<li><p>lorem ipsum</p></li>`

But as I said, this is another level of complexity, of which I have no clue if it is possible at all.

Even ATTO has problems handling paragraphs within list items.

**Comment by jinhofer** [comment]
Ah, I see what you mean. The transformation would be rather difficult, but I actually do that with Word right now, but it isn't easy.

Yeah, Atto takes a minimalist approach to HTML, so it doesn't surprise me that they don't handle \<li>\<p> well.

For now, I'm going to do some testing with the new bits of code and run the UI past the ATTO UI group at my University, then I'll have a new release ready.

**Comment by bwl21** [comment]
Of course. BTW the paste from Markdown use case is different from the markdown text editor in Moodle. The latter stores the text in Markdown which forces everyone to use Markdown then. Even if I would consider this as a good solution, it simply lacks acceptance from the majority of authors.

but If I could at least past markdown this would also bee cool. Maybe this is worth another plugin.

As a pity, it is not simple to convert HTML (in particular messed up HTML) to Markdown. But now I am off topic ...

**Comment by jinhofer** [comment]
I have released a new version on Moodle that includes this feature! Thank you for following up on me with this one to get the release, and sorry it took so long (behat).

**Comment by bwl21** [comment]
I have installed the new version. The two-pane approach is really cool. One can iterate through the options and find the best fit. Thanks a lot.

1. the description of the option is a bit hard to understand. What do you think about: "if checked, paste (cmd-V) invokes paste special"
2. it does not appear if paste is invoked by Menu. So cmd-V and "Paste"-Menu behave differently
3. maybe Shift-Ctrl-V or "Einfügen und Formatvorlage anpassen" ("paste and adjust format") would even be the better shortcut for paste special.
4. The options to paste may also provide the choice to paste the unchanged HTML. As long as we do not handle tables, this is necessary to paste tables e.g. from Excel.
5. would it be possible that if you invoke pasteSpecial by Atto-Button, it pastes the current Clipboard content to the left pane?

**Comment by jinhofer** [comment]
1. I think that would be an improvement. I will run this by some of my coworkers and see what they think.
2. Right clicking will bypass this change, yes. Browsers vary with how they paste, and I feel that there is benefit to allowing users to still bypass the capture (as in tables).
3. I thought about this, but shift-ctrl-v pastes unformatted text within the browser, and I would rather the user utilize that option instead of using my "paste as unformatted"
4. For now, I think that leaving the right click menu as a bypass for my plugin is suitable for this. It's relatively easy to do, though, so if you feel that it is important, I can include it.
5. This is a good idea, but due to security reasons, most browsers require users to allow javascript to access the clipboard for each request, unless they have already deactivated that option.

**Comment by bwl21** [comment]
I would appreciate, if you could implement #4. Then the UI is consistent for the users.

**Comment by jinhofer** [comment]
I have added the option (with associated admin setting) to allow text to be pasted straight in without cleaning the HTML. This has also added three language strings:
$string['pastestraight'] = 'Paste the text without cleaning HTML';
$string['straight'] = 'Paste text straight';
$string['straight_desc'] = 'Allows the user to paste text through pastespecial without cleaning HTML';

Could you translate these and add them to German translation, then send it to me the same way as you did the last one?
